name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
    - uses: tgymnich/publish-github-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
